# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: products
      MYSQL_USER: romulo
      MYSQL_PASSWORD: teste
      MYSQL_ROOT_PASSWORD: teste
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - products_data:/var/lib/mysql

volumes:
  products_data:
